// lib/drillIndex.js
// SkillDrills Pro — Complete Drill Search Index
// Consolidated Cognitive Drills

export const DRILL_INDEX = [
  {
    id: 'batch-processing',
    name: 'Batch Processing',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/attention/batch-processing',
    emoji: '⚙️',
    difficulty: 'beginner',
    keywords: ["batch","processing","cognitive","speed","brain","chunk","group","efficiency"],
  },
  {
    id: 'divided-attention',
    name: 'Divided Attention',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/attention/divided-attention',
    emoji: '🔀',
    difficulty: 'advanced',
    keywords: ["divided","attention","multitask","split","brain","dual","task","simultaneous","cognitive"],
  },
  {
    id: 'multi-tasking',
    name: 'Multi-Tasking',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/attention/multi-tasking',
    emoji: '🎯',
    difficulty: 'advanced',
    keywords: ["multitask","multi","task","brain","dual","simultaneous","cognitive","split","focus"],
  },
  {
    id: 'multiple-targets',
    name: 'Multiple Targets',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/attention/multiple-targets',
    emoji: '⭕',
    difficulty: 'advanced',
    keywords: ["multiple","targets","tracking","visual","multi","follow","several","simultaneous"],
  },
  {
    id: 'selective-attention',
    name: 'Selective Attention',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/attention/selective-attention',
    emoji: '🧠',
    difficulty: 'advanced',
    keywords: ["selective","attention","focus","filter","distraction","concentration","brain","ignore","noise"],
  },
  {
    id: 'conflict-reflex',
    name: 'Conflict Reflex',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/attention/conflict-reflex',
    emoji: '⚡',
    difficulty: 'advanced',
    keywords: ["conflict","reflex","reaction","interference","simon","attention","inhibition","spatial","color","direction"],
  },
  {
    id: 'concentration-grid',
    name: 'Concentration Grid',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/focus/concentration-grid',
    emoji: '🔷',
    difficulty: 'beginner',
    keywords: ["concentration","grid","focus","number","scan","visual","brain","search","find"],
  },
  {
    id: 'distraction-fighter',
    name: 'Distraction Fighter',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/focus/distraction-fighter',
    emoji: '🛡️',
    difficulty: 'impossible',
    keywords: ["distraction","fighter","focus","ignore","noise","filter","brain","concentration"],
  },
  {
    id: 'shade-finder',
    name: 'Shade Finder',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/focus/shade-finder',
    emoji: '🎨',
    difficulty: 'intermediate',
    keywords: ["shade","finder","color","vision","different","square","odd-one-out","focus","concentration"],
  },
  {
    id: 'moving-target',
    name: 'Moving Target',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/focus/moving-target',
    emoji: '🎯',
    difficulty: 'beginner',
    keywords: ["moving","target","tracking","visual","follow","tap","click","aim","accuracy"],
  },
  {
    id: 'card-matching',
    name: 'Card Matching',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/memory/card-matching',
    emoji: '🃏',
    difficulty: 'beginner',
    keywords: ["card","matching","memory","pair","flip","brain","recall","visual","concentration"],
  },
  {
    id: 'grid-memorization',
    name: 'Grid Memorization',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/memory/grid-memorization',
    emoji: '🔷',
    difficulty: 'advanced',
    keywords: ["grid","memorization","spatial","memory","position","location","visual","brain","map"],
  },
  {
    id: 'memory-sequence',
    name: 'Memory Sequence',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/memory/memory-sequence',
    emoji: '🔢',
    difficulty: 'intermediate',
    keywords: ["memory","sequence","order","pattern","brain","recall","series","remember","simon"],
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/problem-solving/sudoku',
    emoji: '🔢',
    difficulty: 'intermediate',
    keywords: ["sudoku","number","grid","puzzle","logic","brain","fill","digit","classic"],
  },
  {
    id: 'tower-of-hanoi',
    name: 'Tower of Hanoi',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/problem-solving/tower-of-hanoi',
    emoji: '🗼',
    difficulty: 'intermediate',
    keywords: ["tower","hanoi","puzzle","brain","recursive","logic","stack","move","solve"],
  },
  {
    id: 'finger-sequencing',
    name: 'Finger Sequencing',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/finger-sequencing',
    emoji: '🤙',
    difficulty: 'intermediate',
    keywords: ["finger","sequence","motor","dexterity","tap","order","pattern","hand","speed"],
  },
  {
    id: 'light-reaction',
    name: 'Light Reaction',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/light-reaction',
    emoji: '💡',
    difficulty: 'beginner',
    keywords: ["light","reaction","visual","speed","flash","tap","stimulus","quick","bright"],
  },
  {
    id: 'quick-dodge',
    name: 'Quick Dodge',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/quick-dodge',
    emoji: '🏃',
    difficulty: 'intermediate',
    keywords: ["quick","dodge","reflex","physical","evade","avoid","reaction","fast","body"],
  },
  {
    id: 'reaction-simulator',
    name: 'Reaction Simulator',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/reaction-simulator',
    emoji: '⚡',
    difficulty: 'beginner',
    keywords: ["simulator","reaction","test","reflex","speed","benchmark","ms","quick"],
  },
  {
    id: 'reaction-time',
    name: 'Reaction Time',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/reaction-time',
    emoji: '⚡',
    difficulty: 'intermediate',
    keywords: ["reaction","time","speed","processing","cognitive","fast","response","brain","quick"],
  },
  {
    id: 'reaction-time-test',
    name: 'Reaction Time Test',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/reaction-time-test',
    emoji: '⚡',
    difficulty: 'beginner',
    keywords: ["reaction","time","test","reflex","speed","response","fast","tap","quick","latency","ms"],
  },
  {
    id: 'reflex-training-drill',
    name: 'Reflex Training',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/reflex-training-drill',
    emoji: '🔥',
    difficulty: 'intermediate',
    keywords: ["reflex","training","reaction","speed","fast","tap","stimulus","response","quick"],
  },
  {
    id: 'symbol-matching',
    name: 'Symbol Matching',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/symbol-matching',
    emoji: '🔣',
    difficulty: 'advanced',
    keywords: ["symbol","matching","processing","speed","brain","visual","pattern","cognitive","fast"],
  },
  {
    id: 'visual-tracking-speed-test',
    name: 'Visual Tracking Speed Test',
    category: 'Cognitive',
    categorySlug: 'cognitive',
    path: '/drills/cognitive/processing-speed/visual-tracking-speed-test',
    emoji: '👁️',
    difficulty: 'advanced',
    keywords: ["visual","tracking","speed","eye","follow","test","benchmark","reaction"],
  },
];

